name: Update data

on:
  repository_dispatch:
    types: [update-data]

jobs:
  pr-development:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout covid19-scraping
        uses: actions/checkout@v2
        with:
          repository: stopcovid19-okayama/covid19-scraping
          ref: 'gh-pages'
          path: 'covid19-scraping'
      - name: Checkout development
        uses: actions/checkout@v2
        with:
          ref: development
          path: development
      - name: Copy data
        run: |
          cp -p covid19-scraping/*.json development/data
      - name: Check diff
        run: |
          cd development
          git diff
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: development
          commit-message: '[BOT] UPDATE DATA $DATE'
          title: '[BOT] UPDATE DATA to development $DATE'
          base: development
          branch: data-bot/development
        env:
          DATE: `date '+%Y-%m-%d'`
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
          echo "Pull Request Number - ${{ steps.cpr.outputs.pr_number }}"
